### ISSUE TITLE
Invalidate approvals on additional changes

### ISSUE THREAD

**Issue by kjvalencik** [paultyng/further-review#7]
If further commits are added to the PR before merge, the PR is still marked as approved. It would be simple to add timestamp checks, but this might not be desired if changes are made to satisfy another reviewer.

**Comment by paultyng** [comment]
It doesn't invalidate approvals, but it does detect new commits on the PR and re-notifies.  Invalidation can probably be built on that? Not sure.

**Comment by paultyng** [comment]
closing in favor of #34
